$(document).ready(function(){cah.log.init();cah.Ajax.build(cah.$.AjaxOperation.FIRST_LOAD).run();if($.cookie("nickname")){$("#nickname").val($.cookie("nickname"));}
$("#nicknameconfirm").click(nicknameconfirm_click);$("#nickbox").keyup(nickbox_keyup);$("#nickbox").focus();$(".chat",$("#tab-global")).keyup(chat_keyup($(".chat_submit",$("#tab-global"))));$(".chat_submit",$("#tab-global")).click(chatsubmit_click(null,$("#tab-global")));$("#logout").click(logout_click);cah.Preferences.load();$("#tabs").tabs();$("#button-global").click();if($.browser.mozilla){$("body").css("font-size","12px");}
$(window).resize(app_resize);app_resize();});$(window).focus(function(){cah.windowActive=true;if(cah.missedGameListRefresh){cah.GameList.instance.update();}});$(window).blur(function(){cah.windowActive=false;});function nickbox_keyup(e){if(e.which==13){$("#nicknameconfirm").click();e.preventDefault();}}
function nicknameconfirm_click(){var nickname=$.trim($("#nickname").val());cah.setCookie("nickname",nickname);var builder=cah.Ajax.build(cah.$.AjaxOperation.REGISTER).withNickname(nickname);if(!cah.noPersistentId&&cah.persistentId){builder.withPersistentId(cah.persistentId);}
builder.run();}
function chat_keyup(submitButton){return function(e){if(e.which==13){$(submitButton).click();e.preventDefault();}};}
function chatsubmit_click(game_id,parent_element){return function(){var ajax=null;var text=$.trim($(".chat",parent_element).val());if(text==""){return;}
var cmd='';if('/'==text.substring(0,1)){cmd=text.substring(1,text.indexOf(' ')>=0?text.indexOf(' '):undefined);if(text.indexOf(' ')>=0){text=text.substring(text.indexOf(' ')+ 1);}else{text='';}}
switch(cmd){case'':if(game_id!==null){ajax=cah.Ajax.build(cah.$.AjaxOperation.GAME_CHAT).withGameId(game_id);}else{ajax=cah.Ajax.build(cah.$.AjaxOperation.CHAT);}
ajax=ajax.withEmote(false).withMessage(text);cah.log.status_with_game(game_id,"<"+ cah.nickname+"> "+ text);break;case'me':if(game_id!==null){ajax=cah.Ajax.build(cah.$.AjaxOperation.GAME_CHAT).withGameId(game_id);}else{ajax=cah.Ajax.build(cah.$.AjaxOperation.CHAT);}
ajax=ajax.withEmote(true).withMessage(text);cah.log.status_with_game(game_id,"* "+ cah.nickname+" "+ text);break;case'wall':ajax=cah.Ajax.build(cah.$.AjaxOperation.CHAT).withWall(true).withMessage(text);break;case'kick':ajax=cah.Ajax.build(cah.$.AjaxOperation.KICK).withNickname(text.split(' ')[0]);break;case'ban':ajax=cah.Ajax.build(cah.$.AjaxOperation.BAN).withNickname(text.split(' ')[0]);break;case'sync':if(game_id!==null){var game=cah.currentGames[game_id];if(game){game.removeAllCards();}
ajax=cah.Ajax.build(cah.$.AjaxOperation.GET_CARDS).withGameId(game_id);}else{cah.log.error("This command only works in a game.");}
break;case'score':ajax=cah.Ajax.build(cah.$.AjaxOperation.SCORE).withMessage(text);if(game_id!=null){ajax=ajax.withGameId(game_id);}
break;case'names':ajax=cah.Ajax.build(cah.$.AjaxOperation.NAMES);break;case'addcardcast':if(game_id!==null){ajax=cah.Ajax.build(cah.$.AjaxOperation.CARDCAST_ADD_CARDSET).withCardcastId(text.split(' ')[0]).withGameId(game_id);}else{cah.log.error("This command only works in a game.");}
break;case'removecardcast':if(game_id!==null){ajax=cah.Ajax.build(cah.$.AjaxOperation.CARDCAST_REMOVE_CARDSET).withCardcastId(text.split(' ')[0]).withGameId(game_id);}else{cah.log.error("This command only works in a game.");}
break;case'listcardcast':if(game_id!==null){ajax=cah.Ajax.build(cah.$.AjaxOperation.CARDCAST_LIST_CARDSETS).withGameId(game_id);}else{cah.log.error("This command only works in a game.");}
break;default:cah.log.error("Invalid command.");}
if(ajax){ajax.run();}
$(".chat",parent_element).val("");$(".chat",parent_element).focus();};}
function logout_click(){if(confirm("Are you sure you wish to log out?")){cah.Ajax.build(cah.$.AjaxOperation.LOG_OUT).run();cah.updateHash('');}}
function preferences_click(){$("#preferences_dialog").dialog({modal:true,buttons:{Ok:function(){save_preferences();$(this).dialog("close");}}});}
function load_preferences(){debugger;cah.Preferences.load();}
function save_preferences(){debugger;cah.Preferences.save();}
function apply_preferences(){debugger;cah.Preferences.apply();}
cah.transferItems=function(sourceListId,destListId,idPrefix){cah.transferItems(sourceListId,destListId,idPrefix,function(a,b){return Number(a.value)- Number(b.value);});};cah.transferItems=function(sourceListId,destListId,idPrefix,sortFunc){$('#'+ sourceListId+' option').filter(':selected').each(function(){var existing=$('#'+ idPrefix+'_'+ this.value);if(existing.length==0){cah.addItem(destListId,this.value,this.text,idPrefix);}});$('#'+ destListId+' option').sort(sortFunc).appendTo('#'+ destListId);cah.removeItems(sourceListId);};cah.addItem=function(listId,value,text,idPrefix){$('#'+ listId).append('<option value="'+ value+'" id="'+ idPrefix+'_'+ value+'">'+ text+'</option>');};cah.removeItems=function(listId){$('#'+ listId+' option').filter(':selected').each(function(){this.parentElement.removeChild(this);});};cah.setCookie=function(name,value){return $.cookie(name,value,{domain:cah.COOKIE_DOMAIN,expires:365});};cah.removeCookie=function(name){$.removeCookie(name,{domain:cah.COOKIE_DOMAIN});};cah.getCookie=function(name){return $.cookie(name);};function app_resize(){var chat=$(".chat",$("#tab-global"));var log=cah.log.log;var chatWidth=$("#canvas").width()- 257;$("#tabs").width(chatWidth+'px');var bottomHeight=$(window).height()- $("#main").height()- $("#menubar").height()- 29;$("#bottom").height(bottomHeight);$("#info_area").height(bottomHeight);$("#tabs").height(bottomHeight);do_app_resize(chat,log);for(var id in cah.currentGames){chat=$(".chat",$("#tab-chat-game_"+ id));log=$(".log",$("#tab-chat-game_"+ id));do_app_resize(chat,log);}
if($(window).height()<650){$("body").css("overflow-y","auto");}else{$("body").css("overflow-y","hidden");}}
function do_app_resize(chatElement,logElement){var chatWidth=$("#canvas").width()- 257;logElement.width((chatWidth+ 2)+'px');chatElement.width((chatWidth- 42)+'px');var bottomHeight=$(window).height()- $("#main").height()- $("#menubar").height()- 29;logElement.height(bottomHeight- chatElement.height()- 40);}