cah.Game=function(id){this.id_=id;this.element_=$("#game_template").clone()[0];this.element_.id="game_"+ id;$(this.element_).removeClass("hide");this.scoreboardElement_=$("#scoreboard_template").clone()[0];this.scoreboardElement_.id="scoreboard_"+ id;$(this.scoreboardElement_).removeClass("hide");this.firstSpectatorElement_=null;this.chatElement_=$("#tab-global").clone()[0];this.chatElement_.id="tab-chat-game_"+ this.id_;$(".chat_submit",this.chatElement_).click(chatsubmit_click(this.id_,this.chatElement_));$(".chat",this.chatElement_).keyup(chat_keyup($(".chat_submit",this.chatElement_)));$(".log",this.chatElement_).empty();this.optionsElement_=$("#game_options_template").clone()[0];this.optionsElement_.id="game_options_"+ id;$("#score_limit_template_label",this.optionsElement_).attr("for","score_limit_"+ id);$("#player_limit_template_label",this.optionsElement_).attr("for","player_limit_"+ id);$("#spectator_limit_template_label",this.optionsElement_).attr("for","spectator_limit_"+ id);$("#card_set_template_label",this.optionsElement_).attr("for","card_set_"+ id);$("#game_password_template_label",this.optionsElement_).attr("for","game_password_"+ id);$("#game_hide_password_template_label",this.optionsElement_).attr("for","game_hide_password_"+ id);$("#timer_multiplier_template_label",this.optionsElement_).attr("for","timer_multiplier_"+ id);$("#score_limit_template",this.optionsElement_).attr("id","score_limit_"+ id);$("#player_limit_template",this.optionsElement_).attr("id","player_limit_"+ id);$("#spectator_limit_template",this.optionsElement_).attr("id","spectator_limit_"+ id);$("#card_set_template",this.optionsElement_).attr("id","card_set_"+ id);$("#game_password_template",this.optionsElement_).attr("id","game_password_"+ id);$("#game_fake_password_template",this.optionsElement_).attr("id","game_fake_password_"+ id);$("#game_hide_password_template",this.optionsElement_).attr("id","game_hide_password_"+ id);$("#timer_multiplier_template",this.optionsElement_).attr("id","timer_multiplier_"+ id);$("#blanks_limit_template",this.optionsElement_).attr("id","blanks_limit_"+ id);for(var key in cah.CardSet.byWeight){var cardSet=cah.CardSet.byWeight[key];var cardSetElementId='card_set_'+ this.id_+'_'+ cardSet.getId();var title=cardSet.getDescription()+' '+ cardSet.getBlackCardCount()+' black card'
+(cardSet.getBlackCardCount()==1?'':'s')+', '+ cardSet.getWhiteCardCount()
+' white card'+(cardSet.getWhiteCardCount()==1?'':'s')+'.';var aria_label=cardSet.getName()+'. '+ title;var html=' <span class="nowrap"><input type="checkbox" id="'+ cardSetElementId
+'" class="card_set" title="'+ title+'" value="'+ cardSet.getId()
+'" name="card_set" aria-label="'+ aria_label+'" /><label for="'+ cardSetElementId
+'" title="'+ title+'" class="card_set_label">'+ cardSet.getName()+'</label></span>';if(cardSet.isBaseDeck()){$(".base_card_sets",this.optionsElement_).append(html);}else{$(".extra_card_sets",this.optionsElement_).append(html);}}
$("label",this.optionsElement_).removeAttr("id");$(".game_options",this.element_).replaceWith(this.optionsElement_);this.host_="";this.scoreCards_={};this.hand_=Array();this.roundCards_={};this.state_=cah.$.GameState.LOBBY;this.blackCard_=null;this.lastBlackCard_=null;this.handSelectedCard_=null;this.roundSelectedCard_=null;this.judge_=null;this.handCardSmallScale_=.35;this.handCardLargeScale_=.6;this.handCardSmallSize_=83;this.handCardLargeSize_=142;this.roundCardSmallScale_=1;this.roundCardLargeScale_=1;this.roundCardSmallSize_=236;this.roundCardLargeSize_=236;this.showingLastRound_=false;this.showingOptions_=true;this.canSelectCard_=true;$("#leave_game").click(cah.bind(this,this.leaveGameClick_));$("#start_game").click(cah.bind(this,this.startGameClick_));$("#stop_game").click(cah.bind(this,this.stopGameClick_));$(".confirm_card",this.element_).click(cah.bind(this,this.confirmClick_));$(".game_show_last_round",this.element_).click(cah.bind(this,this.showLastRoundClick_));$(".game_show_options",this.element_).click(cah.bind(this,this.showOptionsClick_));$("select",this.optionsElement_).change(cah.bind(this,this.optionChanged_));$("input",this.optionsElement_).blur(cah.bind(this,this.optionChanged_));$(".timer_multiplier",this.optionsElement_).change(cah.bind(this,this.optionChanged_));$(".card_set",this.optionsElement_).change(cah.bind(this,this.optionChanged_));$(".game_hide_password",this.optionsElement_).click(cah.bind(this,this.showOrHidePassword_));$(window).on("resize.game_"+ this.id_,cah.bind(this,this.windowResize_));};cah.Game.joinGame=function(gameId){cah.Ajax.build(cah.$.AjaxOperation.GET_GAME_INFO).withGameId(gameId).run();cah.Ajax.build(cah.$.AjaxOperation.GET_CARDS).withGameId(gameId).run();cah.Ajax.build(cah.$.AjaxOperation.CARDCAST_LIST_CARDSETS).withGameId(gameId).run();cah.GameList.instance.hide();var game=new cah.Game(gameId);cah.currentGames[gameId]=game;game.insertIntoDocument();cah.updateHash('game='+ gameId);};cah.Game.prototype.showLastRoundClick_=function(){if(this.showingLastRound_){$(".game_show_last_round",this.element_).attr("value","Show Last Round");$(".game_black_card_round_indicator",this.element_).text("this round is");$(".game_black_card",this.element_).empty().append(this.blackCard_.getElement());$(".game_white_card_wrapper",this.element_).removeClass("hide");$(".game_last_round",this.element_).addClass("hide");}else{$(".game_show_last_round",this.element_).attr("value","Show Current Round");$(".game_black_card_round_indicator",this.element_).text("last round was");$(".game_black_card",this.element_).empty().append(this.lastBlackCard_.getElement());$(".game_white_card_wrapper",this.element_).addClass("hide");$(".game_last_round",this.element_).removeClass("hide");}
this.showingLastRound_=!this.showingLastRound_;};cah.Game.prototype.showOptionsClick_=function(){if(this.showingOptions_){this.showOptions_();}else{this.hideOptions_();}
this.showingOptions_=!this.showingOptions_;};cah.Game.prototype.showOrHidePassword_=function(){if($(".game_hide_password",this.optionsElement_).attr("checked")){$(".game_password",this.optionsElement_).hide();$(".game_fake_password",this.optionsElement_).show();$(".game_fake_password",this.optionsElement_).attr("value",$(".game_password",this.optionsElement_).attr("value"));$(".game_fake_password",this.optionsElement_).attr("disabled","disabled");}else{$(".game_password",this.optionsElement_).show();$(".game_fake_password",this.optionsElement_).hide();}};cah.Game.prototype.getElement=function(){return this.element_;};cah.Game.prototype.setBlackCard=function(card){this.blackCard_=new cah.card.BlackCard(true,card[cah.$.BlackCardData.ID]);this.blackCard_.setText(card[cah.$.BlackCardData.TEXT]);this.blackCard_.setWatermark(card[cah.$.BlackCardData.WATERMARK]);this.blackCard_.setDraw(card[cah.$.BlackCardData.DRAW]);this.blackCard_.setPick(card[cah.$.BlackCardData.PICK]);if(1!=card[cah.$.BlackCardData.PICK]&&this.judge_!=cah.nickname){cah.log.status_with_game(this,"Play "+ card[cah.$.BlackCardData.PICK]
+" cards, in the order you wish them to be judged.");}
if(!this.showingLastRound_){$(".game_black_card",this.element_).empty().append(this.blackCard_.getElement());}};cah.Game.prototype.dealtCards=function(cards){for(var index in cards){var thisCard=cards[index];var card=new cah.card.WhiteCard(true,thisCard[cah.$.WhiteCardData.ID]);card.setText(thisCard[cah.$.WhiteCardData.TEXT]);card.setWatermark(thisCard[cah.$.WhiteCardData.WATERMARK]);card.setIsBlankCard(thisCard[cah.$.WhiteCardData.WRITE_IN]);this.dealtCard(card);}};cah.Game.prototype.dealtCard=function(card){this.hand_.push(card);var element=card.getElement();$(".game_hand_cards",this.element_).append(element);$(element).css("transform-origin","0 0");var data={card:card,};$(element).on("mouseenter.hand",data,cah.bind(this,this.handCardMouseEnter_)).on("mouseleave.hand",data,cah.bind(this,this.handCardMouseLeave_)).on("click.hand",data,cah.bind(this,this.handCardClick_)).on("keypress.hand",data,cah.bind(this,this.handCardKeypress_));this.resizeHandCards_();};cah.Game.prototype.removeCardFromHand=function(card){var cardIndex=-1;for(var index in this.hand_){if(this.hand_[index]==card){cardIndex=index;break;}}
if(cardIndex!=-1){$(card.getElement()).css("width","").css("height","").css("transform-origin","").css("z-index","").css("-moz-transform","").css("-ms-transform","").css("-webkit-transform","").css("-o-transform","").off(".hand");this.hand_.splice(cardIndex,1);}
$(card.getElement(),$("game_hand_cards",this.element_)).remove();this.resizeHandCards_();};cah.Game.prototype.removeAllCards=function(){var handCount=this.hand_.length;for(var i=0;i<handCount;i++){this.removeCardFromHand(this.hand_[0]);}
this.handSelectedCard_=null;$(".confirm_card",this.element_).attr("disabled","disabled");$(".game_black_card",this.element_).empty();for(var index in this.roundCards_){$(this.roundCards_[index]).off(".round");}
this.roundCards_={};$(".game_white_cards",this.element_).empty();};cah.Game.prototype.setRoundWhiteCards=function(cardSets){for(var setIndex in cardSets){var thisSet=Array();for(var index in cardSets[setIndex]){var cardData=cardSets[setIndex][index];var card;var id=cardData[cah.$.WhiteCardData.ID];if(id!=-1){card=new cah.card.WhiteCard(true,id);card.setText(cardData[cah.$.WhiteCardData.TEXT]);card.setWatermark(cardData[cah.$.WhiteCardData.WATERMARK]);}else{card=new cah.card.WhiteCard();}
thisSet.push(card);}
this.addRoundWhiteCard_(thisSet);}};cah.Game.prototype.addRoundWhiteCard_=function(cards){var parentElem;if(cards.length>1){parentElem=$("#game_white_cards_binder_template").clone()[0];parentElem.id="";$(parentElem).removeClass("hide");$(".game_white_cards",this.element_).append(parentElem);}else{parentElem=$(".game_white_cards",this.element_)[0];}
for(var index in cards){var card=cards[index];var element=card.getElement();$(parentElem).append(element);$(element).css("transform-origin","0 0");var data={card:card,};$(element).on("mouseenter.round",data,cah.bind(this,this.roundCardMouseEnter_)).on("mouseleave.round",data,cah.bind(this,this.roundCardMouseLeave_)).on("click.round",data,cah.bind(this,this.roundCardClick_)).on("keypress.round",data,cah.bind(this,this.roundCardKeypress_));}
this.roundCards_[cards[0].getServerId()]=cards;this.resizeRoundCards_();};cah.Game.prototype.handCardMouseEnter_=function(e){if(!$(".game_animate_cards",this.element_).attr("checked")){return;}
$(e.data.card.getElement()).css("z-index","400").animate({scale:this.handCardLargeScale_,width:this.handCardLargeSize_,},{duration:200,queue:false,});};cah.Game.prototype.handCardMouseLeave_=function(e){$(e.data.card.getElement()).animate({scale:this.handCardSmallScale_,"z-index":1,width:this.handCardSmallSize_,},{duration:200,queue:false,});};cah.Game.prototype.roundCardMouseEnter_=function(e){if(!$(".game_animate_cards",this.element_).attr("checked")){return;}
$(e.data.card.getElement()).css("z-index","201").animate({scale:this.roundCardLargeScale_,width:this.roundCardLargeSize_,},{duration:200,queue:false,});};cah.Game.prototype.roundCardMouseLeave_=function(e){$(e.data.card.getElement()).animate({scale:this.roundCardSmallScale_,"z-index":200,width:this.roundCardSmallSize_,},{duration:200,queue:false,});};cah.Game.prototype.windowResize_=function(){this.resizeHandCards_();this.resizeRoundCards_();};cah.Game.prototype.resizeHandCards_=function(){var data={class:".game_hand_cards",cardSmallSize:this.handCardSmallSize_,cardLargeSize:this.handCardLargeSize_,cardSmallScale:this.handCardSmallScale_,cardLargeScale:this.handCardLargeScale_,maxSmallSize:150,minSmallSize:66,smallSize:function(){return($(".game_hand_cards",this.element_).width()- 20)/ ($(".game_hand_cards .card_holder", this.element_).length + 1);},};this.resizeCardHelper_(data);this.handCardSmallSize_=data.cardSmallSize;this.handCardLargeSize_=data.cardLargeSize;this.handCardSmallScale_=data.cardSmallScale;this.handCardLargeScale_=data.cardLargeScale;};cah.Game.prototype.resizeRoundCards_=function(){$(".game_right_side",this.element_).width($(window).width()- $(".game_left_side",this.element_).width()- 30);var data={class:".game_white_cards",cardSmallSize:this.roundCardSmallSize_,cardLargeSize:this.roundCardLargeSize_,cardSmallScale:this.roundCardSmallScale_,cardLargeScale:this.roundCardLargeScale_,maxSmallSize:236,minSmallSize:118,smallSize:function(){return($(window).width()- $(".game_left_side",this.element_).width()- 60)/ $(".game_white_cards .card_holder", this.element_).length;},};this.resizeCardHelper_(data);this.roundCardSmallSize_=data.cardSmallSize;this.roundCardLargeSize_=data.cardLargeSize;this.roundCardSmallScale_=data.cardSmallScale;this.roundCardLargeScale_=data.cardLargeScale;};cah.Game.prototype.resizeCardHelper_=function(data){var elems=$(data.class+" .card_holder",this.element_);data.cardSmallSize=data.smallSize();if(data.cardSmallSize>data.maxSmallSize){data.cardSmallSize=data.maxSmallSize;}
if(data.cardSmallSize<data.minSmallSize){data.cardSmallSize=data.minSmallSize;}
var maxScale=236/data.cardSmallSize;var scale=maxScale<1.8?maxScale:1.8;data.cardLargeSize=data.cardSmallSize*scale;if(data.cardLargeSize>236){data.cardLargeSize=236;}
data.cardSmallScale=data.cardSmallSize/236;data.cardLargeScale=data.cardSmallScale*scale;if(data.cardLargeScale>maxScale){data.cardLargeScale=maxScale;}
elems.width(data.cardSmallSize).height(data.cardSmallSize).animate({scale:data.cardSmallScale,},{duration:0,});};cah.Game.prototype.insertIntoDocument=function(){$("#main_holder").empty().append(this.element_);$("#info_area").empty().append(this.scoreboardElement_);$("#leave_game").show();var linkToChatArea=$("<a>");this.gameChatTab_=$("<li>");linkToChatArea.attr("href","#"+ this.chatElement_.id);linkToChatArea.text("Chat with game members");linkToChatArea.addClass("tab-button");this.gameChatTab_.append(linkToChatArea);$("#tabs ul").append(this.gameChatTab_);$("#tabs").append(this.chatElement_);$("#tabs").tabs("refresh");linkToChatArea.click();this.windowResize_();};cah.Game.prototype.addCardcastDeck=function(data){this.displayCardcastDeckMessage_(data[cah.$.LongPollResponse.CARDCAST_DECK_INFO],"Added");};cah.Game.prototype.removeCardcastDeck=function(data){this.displayCardcastDeckMessage_(data[cah.$.LongPollResponse.CARDCAST_DECK_INFO],"Removed");};cah.Game.prototype.listCardcastDecks=function(cardSets){cah.log.status_with_game(this,"The following <a target='_blank'"
+" href='http://www.cardcastgame.com'>Cardcast</a> decks are in use in this game (<a"
+" target='_blank' href='https://github.com/ajanata/PretendYoureXyzzy/wiki/Cardcast'>"
+"instructions</a>):",'admin',true);for(var key in cardSets){var cardSetData=cardSets[key];this.displayCardcastDeckMessage_(cardSetData,"In use");}};cah.Game.prototype.displayCardcastDeckMessage_=function(deckInfo,verb){var code=("00000"+(-1*deckInfo[cah.$.CardSetData.ID]).toString(36).toUpperCase()).slice(-5);var str=verb+": Cardcast deck '"+ deckInfo[cah.$.CardSetData.CARD_SET_NAME]
+"' (code: <a target='_blank' href='http://www.cardcastgame.com/browse/deck/"+ code+"'> "
+ code+"</a>), with "+ deckInfo[cah.$.CardSetData.BLACK_CARDS_IN_DECK]
+" black cards and "+ deckInfo[cah.$.CardSetData.WHITE_CARDS_IN_DECK]+" white cards.";cah.log.status_with_game(this,str,'admin',true);};cah.Game.prototype.updateGameStatus=function(data){var gameInfo=data[cah.$.AjaxResponse.GAME_INFO];var options=gameInfo[cah.$.AjaxResponse.GAME_OPTIONS];this.host_=gameInfo[cah.$.GameInfo.HOST];if(this.host_==cah.nickname&&gameInfo[cah.$.GameInfo.STATE]==cah.$.GameState.LOBBY){$("#start_game").show();}else{$("#start_game").hide();}
if(this.host_==cah.nickname&&gameInfo[cah.$.GameInfo.STATE]!=cah.$.GameState.LOBBY){$("#stop_game").show();}else{$("#stop_game").hide();}
if(gameInfo[cah.$.GameInfo.STATE]==cah.$.GameState.LOBBY){this.showOptions_();}else{this.hideOptions_();}
$(".score_limit",this.optionsElement_).val(options[cah.$.GameOptionData.SCORE_LIMIT]);$(".player_limit",this.optionsElement_).val(options[cah.$.GameOptionData.PLAYER_LIMIT]);$(".spectator_limit",this.optionsElement_).val(options[cah.$.GameOptionData.SPECTATOR_LIMIT]);$(".game_password",this.optionsElement_).val(options[cah.$.GameOptionData.PASSWORD]);$(".timer_multiplier",this.optionsElement_).val(options[cah.$.GameOptionData.TIMER_MULTIPLIER]);var cardSetIds=options[cah.$.GameOptionData.CARD_SETS];$(".card_set",this.optionsElement_).removeAttr("checked");for(var key in cardSetIds){var cardSetId=cardSetIds[key];$("#card_set_"+ this.id_+"_"+ cardSetId,this.optionsElement_).attr("checked","checked");}
$(".blanks_limit",this.optionsElement_).val(options[cah.$.GameOptionData.BLANKS_LIMIT]);var playerInfos=data[cah.$.AjaxResponse.PLAYER_INFO];for(var index in playerInfos){this.updateUserStatus(playerInfos[index]);}
var spectators=gameInfo[cah.$.GameInfo.SPECTATORS];for(var index in spectators){this.updateSpectator(spectators[index]);}};cah.Game.prototype.updateUserStatus=function(playerInfo){var playerName=playerInfo[cah.$.GamePlayerInfo.NAME];var playerStatus=playerInfo[cah.$.GamePlayerInfo.STATUS];var panel=this.scoreCards_[playerName];if(!panel){panel=new cah.GameScorePanel(playerName);if(this.firstSpectatorElement_){$(this.firstSpectatorElement_).before(panel.getElement());}else{$(this.scoreboardElement_).append(panel.getElement());}
this.scoreCards_[playerName]=panel;}
var oldStatus=panel.getStatus();panel.update(playerInfo[cah.$.GamePlayerInfo.SCORE],playerStatus);if(playerName==cah.nickname){$(".game_message",this.element_).text(cah.$.GamePlayerStatus_msg_2[playerStatus]);if(playerStatus==cah.$.GamePlayerStatus.PLAYING&&this.handSelectedCard_!=null){$(".confirm_card",this.element_).removeAttr("disabled");}else if(playerStatus==cah.$.GamePlayerStatus.JUDGING&&this.roundSelectedCard_!=null){$(".confirm_card",this.element_).removeAttr("disabled");}else{$(".confirm_card",this.element_).attr("disabled","disabled");}
if(playerStatus!=cah.$.GamePlayerStatus.PLAYING){this.handSelectedCard_=null;$(".selected",$(".game_hand",this.element_)).removeClass("selected");}
if(playerStatus==cah.$.GamePlayerStatus.HOST){$("#start_game").show();}
if(playerStatus==cah.$.GamePlayerStatus.JUDGE){$(".game_hand_filter",this.element_).removeClass("hide");$(".game_hand_filter_text",this.element_).text(cah.$.GamePlayerStatus_msg_2[playerStatus]);}else if(playerStatus==cah.$.GamePlayerStatus.PLAYING){$(".game_hand_filter",this.element_).addClass("hide");}}
if(playerStatus==cah.$.GamePlayerStatus.JUDGE||playerStatus==cah.$.GamePlayerStatus.JUDGING){this.judge_=playerName;}
if(oldStatus==cah.$.GamePlayerStatus.PLAYING&&playerStatus==cah.$.GamePlayerStatus.IDLE){if(playerName!=cah.nickname&&this.state_==cah.$.GameState.PLAYING){this.addRoundWhiteCard_(Array(new cah.card.WhiteCard()));}}};cah.Game.prototype.updateSpectator=function(spectator){var panel=this.scoreCards_[spectator];if(!panel){panel=new cah.GameScorePanel(spectator);$(this.scoreboardElement_).append(panel.getElement());this.scoreCards_[spectator]=panel;if(!this.firstSpectatorElement_){this.firstSpectatorElement_=panel.getElement();}}
panel.update(-1,cah.$.GamePlayerStatus.SPECTATOR);if(spectator==cah.nickname){$(".game_message",this.element_).text(cah.$.GamePlayerStatus_msg_2[cah.$.GamePlayerStatus.SPECTATOR]);$(".confirm_card",this.element_).attr("disabled","disabled");}};cah.Game.prototype.roundComplete=function(data){var cards=this.roundCards_[data[cah.$.LongPollResponse.WINNING_CARD]];var ariaText='';for(var index in cards){var card=cards[index];$(".card",card.getElement()).addClass("selected");ariaText+=card.getAriaText();}
var roundWinner=data[cah.$.LongPollResponse.ROUND_WINNER];var scoreCard=this.scoreCards_[roundWinner];$(scoreCard.getElement()).addClass("selected");$(".confirm_card",this.element_).attr("disabled","disabled");cah.log.status_with_game(this,roundWinner+" wins the round.  The next round will begin in "
+(data[cah.$.LongPollResponse.INTERMISSION]/1000)+" seconds.");$(".game_last_round_winner",this.element_).text(roundWinner);$(".game_last_round_cards",this.element_).empty().append($(".game_white_card_wrapper .card_holder",this.element_).clone());this.lastBlackCard_=this.blackCard_;$(".game_show_last_round",this.element_).removeAttr("disabled");cah.log.ariaStatus("The round was won by "+ roundWinner+" with "+ ariaText);};cah.Game.prototype.hurryUp=function(){cah.log.status_with_game(this,"Hurry up! You have less than 10 seconds to decide, or you will be skipped.");};cah.Game.prototype.playerKickedIdle=function(data){cah.log.status_with_game(this,data[cah.$.LongPollResponse.NICKNAME]
+" was kicked for being idle for too many rounds.");};cah.Game.prototype.playerSkipped=function(data){cah.log.status_with_game(this,data[cah.$.LongPollResponse.NICKNAME]
+" was skipped this round for being idle for too long.");};cah.Game.prototype.reshuffle=function(deck){cah.log.status_with_game(this,"The "+ deck+" deck has been reshuffled.");};cah.Game.prototype.judgeLeft=function(data){cah.log.status_with_game(this,"The Card Czar has left the game. Cards played this round are being returned to hands.");cah.log.status_with_game(this,"The next round will begin in "
+(data[cah.$.LongPollResponse.INTERMISSION]/1000)+" seconds.");cah.log.status_with_game(this,"(Displayed state will look weird until the next round.)");};cah.Game.prototype.judgeSkipped=function(){cah.log.status_with_game(this,"The Card Czar has taken too long to decide and has been skipped."
+" Cards played this round are being returned to hands.");};cah.Game.prototype.confirmClick_=function(){if(this.judge_==cah.nickname){if(this.roundSelectedCard_!=null){cah.Ajax.build(cah.$.AjaxOperation.JUDGE_SELECT).withGameId(this.id_).withCardId(this.roundSelectedCard_.getServerId()).run();}}else{if(this.handSelectedCard_!=null){var ajax=cah.Ajax.build(cah.$.AjaxOperation.PLAY_CARD).withGameId(this.id_).withCardId(this.handSelectedCard_.getServerId());if(this.handSelectedCard_.isBlankCard()){var text=prompt("What would you like this card to say?","");if(text==null||text==''){return;}
text=$("<div/>").text(text).html();this.handSelectedCard_.setText(text);ajax=ajax.withMessage(text);}
ajax.run();}}
this.disableCardControls_();};cah.Game.prototype.handCardKeypress_=function(e){if(32==e.which){this.handCardClick_(e);}};cah.Game.prototype.handCardClick_=function(e){if(!this.canSelectCard_){return;}
if(this.judge_==cah.nickname){return;}
var scorecard=this.scoreCards_[cah.nickname];if(scorecard&&scorecard.getStatus()!=cah.$.GamePlayerStatus.PLAYING){return;}
var card=e.data.card;if(this.handSelectedCard_){$(".card",this.handSelectedCard_.getElement()).removeClass("selected");}
if(card==this.handSelectedCard_){this.handSelectedCard_=null;$(".confirm_card",this.element_).attr("disabled","disabled");cah.log.ariaStatus("Deselected card.");}else{this.handSelectedCard_=card;$(".card",card.getElement()).addClass("selected");$(".confirm_card",this.element_).removeAttr("disabled");cah.log.ariaStatus("Selected card.");}};cah.Game.prototype.roundCardKeypress_=function(e){if(32==e.which){this.roundCardClick_(e);}};cah.Game.prototype.roundCardClick_=function(e){if(!this.canSelectCard_){return;}
var scorecard=this.scoreCards_[cah.nickname];if(scorecard&&scorecard.getStatus()!=cah.$.GamePlayerStatus.JUDGING){return;}
var card=e.data.card;if(this.roundSelectedCard_){$(".card",this.roundSelectedCard_.getElement()).removeClass("selected");}
if(card==this.roundSelectedCard_){this.roundSelectedCard_=null;$(".confirm_card",this.element_).attr("disabled","disabled");cah.log.ariaStatus("Deselected card.");}else{this.roundSelectedCard_=card;$(".card",card.getElement()).addClass("selected");$(".confirm_card",this.element_).removeAttr("disabled");cah.log.ariaStatus("Selected card.");}};cah.Game.prototype.leaveGameClick_=function(){if(confirm("Are you sure you wish to leave the game?")){cah.Ajax.build(cah.$.AjaxOperation.LEAVE_GAME).withGameId(this.id_).run();$(this.chatElement_).detach();$(this.gameChatTab_).detach();$("#tabs").tabs("refresh");}};cah.Game.prototype.startGameClick_=function(){cah.Ajax.build(cah.$.AjaxOperation.START_GAME).withGameId(this.id_).run();};cah.Game.prototype.startGameComplete=function(){$("#start_game").hide();};cah.Game.prototype.stopGameClick_=function(){cah.Ajax.build(cah.$.AjaxOperation.STOP_GAME).withGameId(this.id_).run();};cah.Game.prototype.playCardComplete=function(){if(this.handSelectedCard_){$(".card",this.handSelectedCard_.getElement()).removeClass("selected");this.removeCardFromHand(this.handSelectedCard_);this.addRoundWhiteCard_(Array(this.handSelectedCard_));this.handSelectedCard_=null;}
$(".confirm_card",this.element_).attr("disabled","disabled");this.enableCardControls_();};cah.Game.prototype.playCardError=function(){this.enableCardControls_();};cah.Game.prototype.enableCardControls_=function(){this.canSelectCard_=true;};cah.Game.prototype.disableCardControls_=function(){this.canSelectCard_=false;};cah.Game.prototype.dispose=function(){$(this.element_).remove();$(this.scoreboardElement_).remove();$("#leave_game").unbind().hide();$("#start_game").unbind().hide();$("#stop_game").unbind().hide();$(window).off("resize.game_"+ this.id_);cah.updateHash('');};cah.Game.prototype.playerJoin=function(player){if(player!=cah.nickname){cah.log.status_with_game(this,player+" has joined the game.");this.refreshGameStatus();}else{cah.log.status_with_game(this,"You have joined the game.");}};cah.Game.prototype.playerLeave=function(player){if(player!=cah.nickname){cah.log.status_with_game(this,player+" has left the game.");this.refreshGameStatus();}else{cah.log.status_with_game(this,"You have left the game.");}
var scorecard=this.scoreCards_[player];if(scorecard){$(scorecard.getElement()).remove();}
delete this.scoreCards_[player];};cah.Game.prototype.spectatorJoin=function(spectator){if(spectator!=cah.nickname){cah.log.status_with_game(this,spectator+" has started spectating the game.");this.refreshGameStatus();}else{cah.log.status_with_game(this,"You have started spectating the game.");}
this.updateSpectator(spectator);};cah.Game.prototype.spectatorLeave=function(spectator){if(spectator!=cah.nickname){cah.log.status_with_game(this,spectator+" has stopped spectating the game.");this.refreshGameStatus();}else{cah.log.status_with_game(this,"You have stopped spectating the game.");}
var scorecard=this.scoreCards_[spectator];if(scorecard){if(this.firstSpectatorElement_==scorecard.getElement()){this.firstSpectatorElement_=this.firstSpectatorElement_.nextSibling;}
$(scorecard.getElement()).remove();}
delete this.scoreCards_[spectator];};cah.Game.prototype.refreshGameStatus=function(){cah.Ajax.build(cah.$.AjaxOperation.GET_GAME_INFO).withGameId(this.id_).run();};cah.Game.prototype.stateChange=function(data){this.state_=data[cah.$.LongPollResponse.GAME_STATE];$(".scorecard",this.scoreboardElement_).removeClass("selected");switch(this.state_){case cah.$.GameState.LOBBY:this.removeAllCards();this.judge_=null;$(".game_hand_filter",this.element_).addClass("hide");$("#stop_game").hide();this.showOptions_();break;case cah.$.GameState.PLAYING:$(".game_white_cards",this.element_).empty();this.enableCardControls_();this.hideOptions_();this.refreshGameStatus();this.setBlackCard(data[cah.$.LongPollResponse.BLACK_CARD]);break;case cah.$.GameState.JUDGING:$(".game_white_cards",this.element_).empty();this.setRoundWhiteCards(data[cah.$.LongPollResponse.WHITE_CARDS]);break;default:cah.log.error("Game "+ this.id_+" changed to unknown state "+ this.state_);return;}};cah.Game.prototype.hideOptions_=function(){$(".game_show_options",this.element_).val("Show Game Options");$(".game_options",this.element_).addClass("hide");$(".game_right_side",this.element_).removeClass("hide");};cah.Game.prototype.showOptions_=function(){$(".game_show_options",this.element_).val("Hide Game Options");$(".game_options",this.element_).removeClass("hide");$(".game_right_side",this.element_).addClass("hide");this.updateOptionsEnabled_();};cah.Game.prototype.updateOptionsEnabled_=function(){if(this.host_==cah.nickname&&this.state_==cah.$.GameState.LOBBY){$("select",this.optionsElement_).removeAttr("disabled");$("input",this.optionsElement_).removeAttr("disabled");$(".options_host_only",this.optionsElement_).addClass("hide");}else{$("select",this.optionsElement_).attr("disabled","disabled");$("input",this.optionsElement_).attr("disabled","disabled");$(".options_host_only",this.optionsElement_).removeClass("hide");$(".game_hide_password",this.optionsElement_).removeAttr("disabled");}};cah.Game.prototype.optionChanged_=function(e){if(e.target.classList.contains('game_hide_password')){return;}
var selectedCardSets=$(".card_sets :checked",this.optionsElement_);var cardSetIds=[];for(var i=0;i<selectedCardSets.length;i++){cardSetIds.push(selectedCardSets[i].value);}
var options={};options[cah.$.GameOptionData.CARD_SETS]=cardSetIds.join(',');options[cah.$.GameOptionData.SCORE_LIMIT]=$(".score_limit",this.optionsElement_).val();options[cah.$.GameOptionData.PLAYER_LIMIT]=$(".player_limit",this.optionsElement_).val();options[cah.$.GameOptionData.SPECTATOR_LIMIT]=$(".spectator_limit",this.optionsElement_).val();options[cah.$.GameOptionData.PASSWORD]=$(".game_password",this.optionsElement_).val();options[cah.$.GameOptionData.BLANKS_LIMIT]=$(".blanks_limit",this.optionsElement_).val();options[cah.$.GameOptionData.TIMER_MULTIPLIER]=$('.timer_multiplier',this.optionsElement_).val();cah.Ajax.build(cah.$.AjaxOperation.CHANGE_GAME_OPTIONS).withGameId(this.id_).withGameOptions(options).run();};cah.Game.prototype.optionsChanged=function(data){this.updateGameStatus(data);};cah.Game.prototype.getChatElement=function(){return this.chatElement_;};cah.GameScorePanel=function(player){this.player_=player;this.element_=$("#scorecard_template").clone()[0];this.element_.id="";$(this.element_).removeClass("hide");this.score_=0;this.status_=cah.$.GamePlayerStatus.IDLE;$(".scorecard_player",this.element_).text(player);this.update(this.score_,this.status_);};cah.GameScorePanel.prototype.getElement=function(){return this.element_;};cah.GameScorePanel.prototype.update=function(score,status){this.score_=score;this.status_=status;$(".scorecard_score",this.element_).text(score);$(".scorecard_status",this.element_).text(cah.$.GamePlayerStatus_msg[status]);$(".scorecard_s",this.element_).text(score==1?"":"s");if(score<0){$(".scorecard_points",this.element_).addClass("hide");$(this.element_).attr("aria-label",this.player_+". "+ cah.$.GamePlayerStatus_msg[status]);}else{$(".scorecard_points",this.element_).removeClass("hide");$(this.element_).attr("aria-label",this.player_+" has "+ score+" Awesome Point"+(score==1?"":"s")+". "
+ cah.$.GamePlayerStatus_msg[status]);}};cah.GameScorePanel.prototype.getStatus=function(){return this.status_;};